version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - phpapp

  db:
    image: mysql:8.0
    restart: always
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: php_mvc_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - phpapp

  php:
    container_name: php-container
    build: ./php
    ports:
      - "9000:9000"
    environment:
      APP_ENV: dev
    volumes:
      - ../:/var/www/html
    networks:
      - phpapp


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '8081:80'
    depends_on:
      - db
    networks:
      - phpapp

networks:
  phpapp:
